### ISSUE TITLE
Bootstrap.css Unexpected character '@'

### ISSUE THREAD

**Issue by hrishikeshqb** [fyockm/bootstrap-css-only#19]
Hi,

Iam trying to use bootstrap-css-only with webpack. Here is my config 
```js
var webpack = require('webpack');

module.exports = {
  context: __dirname + '/src',
  entry: {
    app: './app.js',
    vendor: ['angular', 'angular-ui-router', 'jquery', 'bootstrap-only-css']
  },
  devtool: 'source-map',
  output: {
    path: __dirname + '/js',
    filename: 'app.bundle.js'
  },
  module:{
    loaders: [
      {
        test: /\.scss$/,
        loader: "style!css!sass",
        exclude: /node_modules/
    },
      {
        test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url?limit=10000&mimetype=application/font-woff'
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url?limit=10000&mimetype=application/octet-stream'
      },
      {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'file'
      },
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url?limit=10000&mimetype=image/svg+xml'
      }
    ],
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      moment: "moment"
    })
  ]
};
```

but the build always shows the error 

>  28% 3/10 build modulesModuleParseError: Module parse failed: /node_modules/bootstrap-only-css/dist/bootstrap.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)

Do I need to add any other loaders to solve this issue?

**Comment by fyockm** [comment]
@hrishikeshqb Not sure if this is actually part of the problem, but the first thing I notice is that your config has "bootstrap-only-css", while the name of the package is "bootstrap-css-only".

I'm definitely not a webpack expert, but according to [this webpack issue](https://github.com/webpack/css-loader/issues/38), it looks like you may need something else?

**Comment by hrishikeshqb** [comment]
@fyockm Thanks for the heads up man and excuse me for the late reply.
Changed the package name and ran into another set of errors while building

> node_modules/bootstrap-css-only/css/bootstrap.min.css Unexpected token (5:83)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:83)
 
Also following up the issue you just mentioned. Modified my config as follows 

`var webpack = require('webpack');`
`module.exports = {`
`  context: __dirname + '/src',`
 ` entry: {`
    `app: './app.js',`
    `vendor: ['angular', 'angular-ui-router', 'angular-bootstrap-calendar', 'bootstrap-css-only']`
  `},`
  `output: {`
    `path: __dirname + '/js',`
    `filename: 'app.bundle.js'`
  `},`
  `module:{`
    `loaders: [`
      `{`
        `test: /\.scss$/,`
        `loader: "style!css!sass",`
      `},`
      `{ test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }`
    `],`
  `},`
  `plugins: [`
    `new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js")`
  `]`
`};`

**Comment by hrishikeshqb** [comment]
@fyockm I was in short of a css-loader to handle all the css files. I guess that fixed the issue.  Here is my array of loaders 
   ` loaders: [`
     `{
        test: /\.scss$/,
        loader: "style!css!sass",
      },`
      `{
        test: /\.css$/,
        loader: "style!css",
      },`
      `{ test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }
    ]`

Hence closing the issue, thanks again @fyockm!

**Comment by fyockm** [comment]
@hrishikeshqb glad you got it figured out! sorry I wasn't able to offer more help.
