### ISSUE TITLE
Reversion on latest version

### ISSUE THREAD

**Issue by Biohazord** [fyockm/bootstrap-css-only#21]
It appears as though you've published 2.3.2-1 as the latest version on NPM. When I do 
`npm view bootstrap-css-only`

I get back the following
`'dist-tags': { latest: '2.3.2-1' },
versions: [ '2.3.2-1', '2.3.2', '3.3.5', '3.3.6', '3.3.7' ]`
According to the time tag it appears as though 2.3.2 was published twice on March 10th 2017.

Temporary workaround is to install bootstrap-css-only@3.3.7

**Comment by fyockm** [comment]
@Biohazord Sorry about that. Someone asked me to publish 2.3.2 on npm a little while ago, and in doing, it apparently messed up `latest`. Thanks for bringing to my attention.

So, I've just learned that there's actually an npm command to update the `dist-tag`. I have set `bootstrap-css-only@latest` back to `3.3.7`.
