### ISSUE TITLE
Publish v4 to npm with 'beta' tag to keep consistent behavior with 'bootstrap' module.

### ISSUE THREAD

**Issue by ravshansbox** [fyockm/bootstrap-css-only#25]
Publish v4 to npm with 'beta'/'next' tag to keep consistent behavior with 'bootstrap' module.
'bootstrap' module by default installs v3 with 'npm install bootstrap' and v4 with 'npm install bootstrap@next'.

**Comment by fyockm** [comment]
hi @ravshansbox, I've updated the `dist-tags` for bootstrap-css-only to mirror `bootstrap` proper.

Now the output from `npm info bootstrap-css-only` shows:
```
'dist-tags': { latest: '3.3.7', next: '4.0.0-beta.2' },
```

**Comment by ravshansbox** [comment]
Thanks.
