### ISSUE TITLE
Update to 4.4.1

### ISSUE THREAD

**Issue by mediatec** [fyockm/bootstrap-css-only#47]
4.4.1 was released - https://github.com/twbs/bootstrap/releases

Please update it, thank you :)

**Comment by pglejzer** [comment]
+1 
@ravshansbox 
@fyockm 
are you gonna update to the latest version?

**Comment by pglejzer** [comment]
I just made a new package with the latest version of Bootstrap so if you don't want to wait to update this package just use mine.

**Comment by fyockm** [comment]
you could have just submitted a PR here, or i'd be happy to make you a maintainer, since there's already some usage.

i no longer use this repo, personally.

**Comment by fyockm** [comment]
`bootstrap-css-only@4.4.1` published to npm

**Comment by pglejzer** [comment]
Thank you for the update. So it is not a problem I can be a maintainer. I'm working with bootstrap every day so I'm up to date with this.
