### ISSUE TITLE
woff2 - where is it?

### ISSUE THREAD

**Issue by matanshukry** [fyockm/bootstrap-css-only#5]
the file glyphicons-halflings-regular.woff2 is missing from this repository.
Is there any reason for that? If not, can it be added?

**Comment by fyockm** [comment]
@matanshukry thanks for pointing out the oversight.

**Comment by matanshukry** [comment]
fyockm - you forgot to also update bower.json file. You need to add the woff2 in there.
Currently i'm getting 'invalid meta missing ignoer entry' when trying to install it using bower.
